"""Constants for the venstar integration."""

from venstarcolortouch import VenstarColorTouch

from homeassistant.components.climate.const import (
    HVAC_MODE_AUTO,
    HVAC_MODE_COOL,
    HVAC_MODE_HEAT,
    HVAC_MODE_OFF,
)
from homeassistant.const import (
    DEVICE_CLASS_BATTERY,
    DEVICE_CLASS_HUMIDITY,
    DEVICE_CLASS_TEMPERATURE,
    PERCENTAGE,
    STATE_ON,
    TEMP_CELSIUS,
    TEMP_FAHRENHEIT,
)

api = VenstarColorTouch(
    addr="",
    timeout=0,
)

VENSTAR_API_VER = "_api_ver"
VENSTAR_AWAY = "away"
VENSTAR_AWAY_AWAY = api.AWAY_AWAY
VENSTAR_AWAY_HOME = api.AWAY_HOME
VENSTAR_COOLTEMP = "cooltemp"
VENSTAR_DEHUM_SETPOINT = "dehum_setpoint"
VENSTAR_FAN = "fan"
VENSTAR_FAN_AUTO = api.FAN_AUTO
VENSTAR_FAN_ON = api.FAN_ON
VENSTAR_FANSTATE = "fanstate"
VENSTAR_FANSTATE_OFF = api.FANSTATE_OFF
VENSTAR_FANSTATE_ON = api.FANSTATE_ON
VENSTAR_HEATTEMP = "heattemp"
VENSTAR_HUM_ACTIVE = "hum_active"
VENSTAR_HUM_SETPOINT = "hum_setpoint"
VENSTAR_MODE = "mode"
VENSTAR_MODE_AUTO = api.MODE_AUTO
VENSTAR_MODE_COOL = api.MODE_COOL
VENSTAR_MODE_HEAT = api.MODE_HEAT
VENSTAR_MODE_OFF = api.MODE_OFF
VENSTAR_MODEL = "model"
VENSTAR_NAME = "name"
VENSTAR_SCHEDPART_DAY = api.SCHEDPART_DAY
VENSTAR_SCHEDPART_EVENING = api.SCHEDPART_EVENING
VENSTAR_SCHEDPART_INACTIVE = api.SCHEDPART_INACTIVE
VENSTAR_SCHEDPART_MORNING = api.SCHEDPART_MORNING
VENSTAR_SCHEDPART_NIGHT = api.SCHEDPART_NIGHT
VENSTAR_SCHEDULE = "schedule"
VENSTAR_SCHEDULE_DISABLED = 0
VENSTAR_SCHEDULE_ENABLED = 1
VENSTAR_SCHED_C = api.SCHED_C
VENSTAR_SCHED_F = api.SCHED_F
VENSTAR_SETPOINT_DELTA = "setpoint_delta"
VENSTAR_STATE = "state"
VENSTAR_STATE_COOLING = api.STATE_COOLING
VENSTAR_STATE_ERROR = api.STATE_ERROR
VENSTAR_STATE_HEATING = api.STATE_HEATING
VENSTAR_STATE_IDLE = api.STATE_IDLE
VENSTAR_STATE_LOCKOUT = api.STATE_LOCKOUT
VENSTAR_TEMPUNITS = "tempunits"
VENSTAR_TEMPUNITS_C = api.TEMPUNITS_C
VENSTAR_TEMPUNITS_F = api.TEMPUNITS_F
VENSTAR_TYPE = "_type"

del api

ATTR_FAN_STATE = "fan_state"
ATTR_HVAC_STATE = "hvac_mode"

DOMAIN = "venstar"

CONF_HUMIDIFIER = "humidifier"

DEFAULT_CONF_HUMIDIFIER = False
DEFAULT_CONF_PASSWORD = ""
DEFAULT_CONF_PIN = ""
DEFAULT_CONF_PORT = ""
DEFAULT_CONF_SCAN_INTERVAL = 10
DEFAULT_CONF_SENSORS = True
DEFAULT_CONF_SSL = False
DEFAULT_CONF_TIMEOUT = 5
DEFAULT_CONF_USERNAME = ""

ENTRY_API = "api"
ENTRY_CONNECTION_STATE = "connection_state"
ENTRY_COORDINATOR = "coordinator"
ENTRY_UNDO_UPDATE_LISTENER = "undo_update_listener"

HOLD_MODE_OFF = "off"
HOLD_MODE_TEMPERATURE = "temperature"

MODE_MAP = {
    HVAC_MODE_HEAT: VENSTAR_MODE_HEAT,
    HVAC_MODE_COOL: VENSTAR_MODE_COOL,
    HVAC_MODE_AUTO: VENSTAR_MODE_AUTO,
}

SENSOR_BATTERY = "battery"
SENSOR_HUMIDITY = "hum"
SENSOR_ID = "id"
SENSOR_TEMPERATURE = "temp"

SENSOR_PARAM_CLASS = "class"
SENSOR_PARAM_NAME = "name"
SENSOR_PARAM_UNIT = "unit"

SENSOR_ATTRIBUTES = {
    SENSOR_BATTERY: {
        SENSOR_PARAM_NAME: "Battery Level",
        SENSOR_PARAM_CLASS: DEVICE_CLASS_BATTERY,
        SENSOR_PARAM_UNIT: PERCENTAGE,
    },
    SENSOR_HUMIDITY: {
        SENSOR_PARAM_NAME: "Humidity",
        SENSOR_PARAM_CLASS: DEVICE_CLASS_HUMIDITY,
        SENSOR_PARAM_UNIT: PERCENTAGE,
    },
    SENSOR_ID: {SENSOR_PARAM_NAME: "ID"},
    SENSOR_TEMPERATURE: {
        SENSOR_PARAM_NAME: "Temperature",
        SENSOR_PARAM_CLASS: DEVICE_CLASS_TEMPERATURE,
        SENSOR_PARAM_UNIT: {
            VENSTAR_TEMPUNITS_F: TEMP_FAHRENHEIT,
            VENSTAR_TEMPUNITS_C: TEMP_CELSIUS,
        },
    },
}

VALID_FAN_STATES = [STATE_ON, HVAC_MODE_AUTO]
VALID_THERMOSTAT_MODES = [HVAC_MODE_HEAT, HVAC_MODE_COOL, HVAC_MODE_OFF, HVAC_MODE_AUTO]
